tools:
  go:
    - latest
    - 1.22.0
    - 1.23rc1
  node:
    - latest
  deno:
    - latest
  ruby:
    - "3.1"
  python: 
    - latest
  rye: 
    - latest
settings:
  jobs: 4
  experimental: true

